apiVersion: v1
kind: Service
metadata:
  name: medscloud-frontend-service
spec:
  selector:
    app.kubernetes.io/name: medscloud-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
