apiVersion: v1
kind: Service
metadata:
  name: medscloud-frontend-service
spec:
  selector:
    app.kubernetes.io/name: medscloud-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
